INSERT INTO config (name, value, desc) VALUES ('LISTEN_PORT4TASKSERVER', '12345', 'Task TCP主动监听端口');
INSERT INTO config (name, value, desc) VALUES ('TASK_SERVER', 'http://192.168.4.40:8080/testweb', 'Task Server 地址');
INSERT INTO config (name, value, desc) VALUES ('FILE_SERVER', 'http://127.0.0.1:80', '文件服务器地址');
INSERT INTO config (name, value, desc) VALUES ('LISTEN_PORT4RDP', '9299', 'RDP报文监听端口');
INSERT INTO config (name, value, desc) VALUES ('RDP_PORT', '9299', 'RDP报文发送端口');
INSERT INTO config (name, value, desc) VALUES ('TASK_LOOP_TIME', '120', 'Http 轮询时间间隔,单位秒');
INSERT INTO config (name, value, desc) VALUES ('ATMC_VER', '0', 'atmc版本号');
INSERT INTO config (name, value, desc) VALUES ('AGENT_VER', '0', 'agent版本号.');
INSERT INTO config (name, value, desc) VALUES ('DEV_NUM', '13345678', '设备编号');
INSERT INTO config (name, value, desc) VALUES ('TRNEJ', '0000', '命令流水号');
INSERT INTO config (name, value, desc) VALUES ('CTIME', '0000', 'C端发包时间');
INSERT INTO config (name, value, desc) VALUES ('NEW_SOF_VER', 'ADV-2.0.0', '最新软件版本号');
INSERT INTO config (name, value, desc) VALUES ('NEW_ADV_VER', '', '最新广告版本号');
INSERT INTO config (name, value, desc) VALUES ('NEW_CFG_VER', 'CFG-2.0.0', '最新配置版本号');
INSERT INTO config (name, value, desc) VALUES ('OLD_SOF_VER', '', '旧软件版本号');
INSERT INTO config (name, value, desc) VALUES ('OLD_ADV_VER', '', '旧广告版本号');
INSERT INTO config (name, value, desc) VALUES ('OLD_CFG_VER', '0000', '旧配置版本号');
INSERT INTO config (name, value, desc) VALUES ('OLD_AGENT_VER', '1.0.0', '旧agent版本号');
INSERT INTO config (name, value, desc) VALUES ('PUSHSVRIP', '10.10.10.11', '推送服务器地址');
INSERT INTO config (name, value, desc) VALUES ('PUSHSVRPORT', '9010', '推送服务器端口 ');
INSERT INTO config (name, value, desc) VALUES ('EJSVR', '10.10.10.10', '电子流水地址');
INSERT INTO config (name, value, desc) VALUES ('EJSVRPORT', '9009', '电子流水端口');
INSERT INTO config (name, value, desc) VALUES ('AMSIP', '10.10.10.11', '状态监控服务IP');
INSERT INTO config (name, value, desc) VALUES ('AMSTCPPORT', '8887', '监控服务TCP端口');
INSERT INTO config (name, value, desc) VALUES ('AMSUDPPORT', '8888', '监控服务UDP端口');
INSERT INTO config (name, value, desc) VALUES ('SENDINTERVAL', '300', '监控报文发送间隔(秒)');
INSERT INTO config (name, value, desc) VALUES ('EJUPLOAD', '1', '1-上传电子流水，0-不上传电子流水');
INSERT INTO config (name, value, desc) VALUES ('EJONLY', '0', '只打印电子流水不打印纸质流水（ejupload必须为1才有效），0-打印电子流水和纸质流水');
INSERT INTO config (name, value, desc) VALUES ('EJTORLERANT', '1', '电子流水丢失容忍笔数，硬盘未坏');
INSERT INTO config (name, value, desc) VALUES ('EJHDDTOLERANT', '50', '电子流水丢失容忍笔数，硬盘已坏');
INSERT INTO config (name, value, desc) VALUES ('TRANSINFOBATCH', '25', '对账报文批量上传笔数');
INSERT INTO config (name, value, desc) VALUES ('FILELIMIT', '10240', '上传文件大小限制(KB)');